version: 2.1

jobs:
  build:
    docker:
      - image: cibuilds/docker:19.03
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: "Build Docker Image(s)"
          command: |
            chmod +x ./build-images.sh
            ./build-images.sh
      - deploy:
          name: "Publish Docker Image(s) (master branch only)"
          command: |
            if [ "${CIRCLE_BRANCH} == "master" ]; then
              echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
            
              # an else block will be added in the future for a staging release
              if git log -1 --pretty=$s | grep "\[release\]"; then
                echo "Publishing mfunaki/node to Docker Hub production."
                docker push mfunaki/node
              else
                echo "Skipping publishing."
              fi
            fi